group: edge
sudo: required
dist: trusty
services:
    - docker

env:
    global:
        - secure: "q789gYRu9IOQEnElAhKODZtMTpV0/5QNuu0n1C0FKGettX5Okc0FSQszufZqryf2XL6E0F35WkeXpSWf6LyS5x66Knn1rxf0UAodhEdApUpmCCFfemmd+nT7+2g0PvE5TvlDd+C4M1guCRy/ET6OftPOegrGdipGMy9fWwbAPo9Ic4J3t+4J8xS/r8FWz8BCbhv0sdWa0vZsEJ1e1t4IHFUIh6fz8KplZbsjjH3Dai7kyoKa4XqyDHE43uto7Fid3PsTjqslTLL5qZeUNDa1+y6eLfGzNGlgbycaBgaLMW+5Yf+sm5RwBLRr2e7EaDuMVZ+GZJXuScbGJ9f1t/AYnq2mzR2YUBI+lqFtApKu9iRJg2kFt2Y926rEv0UoIqhffiou0LK0B7Ca2TtfA3+qK5GmDm0CCRfddq12h5B7xUu1MaYpLq07kRJGobgGdzoNkZ/+CrFrLc9iPsmyIIdx1Rg7Eq38c3V25Q6/EcsRkUQKrO1IRzOfWg1BgBAb+vV4t6urNtiS0WrCsysxiDy8PPuOhK61qTMt28E/M12eaBe+i/d5y7HV9tRKTZM22VEnZCyv38Iz2R/u1RyQq7Cw2JqqKtiuVPoVYbnnDgzvAo9yd1gIfEBT7Ot6+HAHllerTZiZ7GMQ3pwKiwrIFd8TlWe9hPNNrQnZ9LBp6uwNsAA="
        - secure: "Zx+qqPgegeo2EYVHyQiZbTurnmyHLwc+xunKuUHY9kWkZdqpsO57o8spoI62aF7cK+Lidakceq+u4p1/Tunzch/drPgv4Ng6n+cJxjuqT+Z5TJMjOtGJcNtlK5Z9seG6Tp7ZuHI9EWXVK3K7y08D/ByN0gB5Wx5Wo/hm2FTnixNf+j+PX8wHu3j4xI4Td21M+0R5eHvDGaUxuC9iiEcsZpiVov3Vty9JXxxih2EsTTKTQaPYXthZ/8erMDpIobljG8gDd5dL9wEanPhhYLwC8b0RSr1F7TUVJwbHpm1GK662rHI7VG5r/wOLc4FspX+mUItaSqreJVRINVjT08kxtgOfhrpmNq3LYBlmebLC8ifLa1+IXYt68+d2ZoLu35hW4UryJkZlDWTYhWQpzTb3UKTh/TgkrpHnN9TSTfYJ0n3taZ3ehw26nZcvUUS7JpNwMbu1ukKyv/ixRXZ7f5qQa1djeNBXqS7msoYeuY9HURj6KbHqKtz/tB0v+3cNg7VY4H4CHQ86et3+W2Ce1ATQshuTmERYkSObSUGMh35U1ReSEKcPl3QdIHk137wwYMxFPdpbiq1Xkds0o6DBdlWbfcuyF3Eog7opBAenXKm1qSmUSu1m9aoT8t0L1PVy9WG68B5x8xPA0wroELQkRVYQ3U+L40d2o857lXaFOarHsNc="
        - GRADLE_VERSION='4.2'
language: java
jdk:
    - oraclejdk8
    - oraclejdk9
    - openjdk8
    - ibmjava8
before_install:
    - ( cd $HOME && curl -LO "https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip" )
    - ( cd $HOME && unzip -q gradle-$GRADLE_VERSION-bin.zip && rm gradle-$GRADLE_VERSION-bin.zip )
    - export PATH=$HOME/gradle-$GRADLE_VERSION/bin:$PATH && hash -r && gradle --version
script:
    - gradle test
    - gradle checkstyle{Main,Test}
    - gradle clean testJar
    - docker build -t rxb .
    - scripts/test rxbroadcast.integration.SingleSourceFifoOrderUdpBroadcastTest 'sudo tc qdisc add dev "${DOCKER_IFACE%%@if+([0-9])}" root netem delay 100ms 75ms'
    - scripts/test rxbroadcast.integration.NoOrderUdpBroadcastTest
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpNoOrder
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpNoOrderKryoSerializer
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpNoOrderObjectSerializer
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpSingleSourceFifoOrder
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpSingleSourceFifoOrderKryoSerializer
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpSingleSourceFifoOrderObjectSerializer
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpSingleSourceFifoOrderProtobufSerializer
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpCausalOrder
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpCausalOrderKryoSerializer
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpCausalOrderObjectSerializer
    - scripts/test-table-tennis rxbroadcast.integration.pp.PingPongUdpCausalOrderProtobufSerializer
jobs:
    allow_failures:
        - stage: "Test"
          jdk: oraclejdk9
        - stage: "Test"
          jdk: ibmjava8
    include:
        - stage: "Static analysis"
          jdk: oraclejdk8
          addons:
              apt:
                  sources:
                      - avsm
                  packages:
                      - aspcud
                      - autoconf
                      - automake
                      - gcc
                      - g++
                      - git
                      - groff-base
                      - libc6-dev
                      - libgmp-dev
                      - libmpc-dev
                      - libmpfr-dev
                      - m4
                      - make
                      - ncurses-dev
                      - ocaml
                      - opam
                      - pkg-config
                      - python2.7
                      - rsync
                      - unzip
                      - zlib1g-dev
          env:
              - INFER_VERSION='0.12.1'
              - INFER_DIRECTORY='/opt/infer'
          cache:
              directories:
                  - "$INFER_DIRECTORY"
          script: scripts/infer
        - script: gradle findBugs{Main,Test}
        - script: gradle errorProne
        - script: gradle pmd{Main,Test}
        - stage: "Mutation testing"
          jdk: oraclejdk8
          script: gradle pitest
deploy:
    provider: script
    script: .travis/deploy
    on:
        jdk: openjdk8
        tags: true
notifications:
    email: false
